-- Migration for Master Admin and Billing System

-- 1. Update users table with new columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS access_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS access_override BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_access_at TIMESTAMP WITH TIME ZONE;

-- Normalize role case/values if needed (ensure role is text and can handle MASTER/ADMIN)
-- The default is 'cliente', we will use 'MASTER' and 'ADMIN' for management

-- 2. Create billing_installments table
CREATE TABLE IF NOT EXISTS billing_installments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    competence_month TEXT NOT NULL, -- Format: YYYY-MM
    due_date DATE NOT NULL,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 10.00,
    status TEXT NOT NULL DEFAULT 'A_VENCER', -- A_VENCER, VENCIDA, PAGA
    paid_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. RLS Policies
-- NOTE: ROW LEVEL SECURITY is being disabled because the current architecture 
-- uses a custom authentication system in AuthService.js that is not yet 
-- integrated with Supabase Auth. To allow the Master Admin to manage 
-- billing, we will follow the pattern of the other tables in the project.
ALTER TABLE billing_installments DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS master_manage_all_billing ON billing_installments;
DROP POLICY IF EXISTS admin_view_own_billing ON billing_installments;


-- 4. Initial Master Admin Seed (optional, will also be handled by JS init)
-- Note: id might be serial or uuid, using fallback logic in JS is safer.
