-- ============================================================================
-- MALIBU CRÉDITO — MIGRATION V2: MULTI-TENANT ASAAS SECURE
-- ============================================================================
-- Execute este script NO SQL Editor do Supabase (Dashboard > SQL Editor)
-- ORDEM OBRIGATÓRIA: Execute de cima para baixo.
-- ============================================================================

-- ============================================================================
-- 1. TABELA: company_integrations
-- Armazena credenciais ASAAS criptografadas POR EMPRESA.
-- A api_key NUNCA é exposta ao frontend — apenas a Edge Function com
-- MASTER_ENCRYPTION_KEY pode descriptografar.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.company_integrations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    provider            TEXT NOT NULL DEFAULT 'asaas',   -- 'asaas' | 'stripe' | ...
    environment         TEXT NOT NULL DEFAULT 'sandbox', -- 'sandbox' | 'production'
    api_key_encrypted   TEXT,          -- AES-256-GCM encrypted, base64-encoded
    api_key_iv          TEXT,          -- Initialization vector, base64-encoded
    webhook_token       TEXT,          -- Token aleatório para validar chamadas do ASAAS
    is_enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    last_test_ok        BOOLEAN,
    last_test_at        TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (company_id, provider)
);

-- ============================================================================
-- 2. TABELA: logs_webhook
-- Auditoria de todos os eventos recebidos via webhook ASAAS por empresa.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.logs_webhook (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      INT REFERENCES public.companies(id) ON DELETE SET NULL,
    provider        TEXT NOT NULL DEFAULT 'asaas',
    event_type      TEXT,              -- ex: PAYMENT_RECEIVED, PAYMENT_CONFIRMED
    asaas_event_id  TEXT,              -- ID único do evento no ASAAS (idempotency)
    payload         JSONB,             -- Payload bruto recebido
    received_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    processed_ok    BOOLEAN DEFAULT FALSE,
    error_message   TEXT
);

CREATE INDEX IF NOT EXISTS idx_logs_webhook_company_id ON public.logs_webhook(company_id);
CREATE INDEX IF NOT EXISTS idx_logs_webhook_event_type ON public.logs_webhook(event_type);
CREATE UNIQUE INDEX IF NOT EXISTS uidx_logs_webhook_event_id
    ON public.logs_webhook(provider, asaas_event_id)
    WHERE asaas_event_id IS NOT NULL;

-- ============================================================================
-- 3. AJUSTES NA TABELA pix_charges
-- Adicionar campos necessários para multi-tenant seguro.
-- ============================================================================
ALTER TABLE public.pix_charges ADD COLUMN IF NOT EXISTS asaas_payment_id TEXT;
ALTER TABLE public.pix_charges ADD COLUMN IF NOT EXISTS pix_payload       JSONB;
ALTER TABLE public.pix_charges ADD COLUMN IF NOT EXISTS paid_at           TIMESTAMP WITH TIME ZONE;

-- Índice único: uma cobrança ASAAS não pode aparecer em outra empresa
CREATE UNIQUE INDEX IF NOT EXISTS uidx_pix_charges_company_asaas
    ON public.pix_charges(company_id, asaas_payment_id)
    WHERE company_id IS NOT NULL AND asaas_payment_id IS NOT NULL;

-- ============================================================================
-- 4. MIGRAÇÃO DE DADOS — Mover asaas_api_key de companies para company_integrations
-- NOTA: Como a API key estava em texto plano, vamos apenas registrar que
-- ela precisa ser reconfigurada. A coluna será removida após a migração.
-- ============================================================================
DO $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN
        SELECT id, asaas_api_key, asaas_environment
        FROM public.companies
        WHERE asaas_api_key IS NOT NULL AND asaas_api_key != ''
    LOOP
        -- Inserir em company_integrations com api_key_encrypted = NULL
        -- O admin deverá reconfigurar via UI para que a key seja encriptada
        INSERT INTO public.company_integrations
            (company_id, provider, environment, api_key_encrypted, api_key_iv, webhook_token, is_enabled)
        VALUES (
            rec.id,
            'asaas',
            COALESCE(rec.asaas_environment, 'sandbox'),
            NULL,   -- Será preenchido ao salvar via UI (criptografado)
            NULL,
            encode(gen_random_bytes(32), 'hex'), -- Token aleatório seguro
            TRUE
        )
        ON CONFLICT (company_id, provider) DO NOTHING;
    END LOOP;
END $$;

-- ============================================================================
-- 5. FUNÇÕES AUXILIARES PARA RLS
-- ============================================================================

-- Verifica se usuário logado é MASTER (email específico ou role)
CREATE OR REPLACE FUNCTION public.is_master()
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.users
        WHERE id::text = auth.uid()::text
          AND (role = 'MASTER' OR email = 'ivanrossi@outlook.com')
    );
$$;

-- Retorna o company_id do usuário logado (NULL se master)
CREATE OR REPLACE FUNCTION public.get_user_company_id()
RETURNS INT
LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT company_id FROM public.users
    WHERE id::text = auth.uid()::text
    LIMIT 1;
$$;

-- ============================================================================
-- 6. RLS — HABILITAR E CONFIGURAR POLICIES
-- ATENÇÃO: Este sistema usa auth customizado (não Supabase Auth JWT).
-- As políticas abaixo usam service role key para operações do backend.
-- As tabelas sensíveis ficam acessíveis SOMENTE via service_role (backend).
-- ============================================================================

-- company_integrations: APENAS service_role pode ler/escrever
-- (Frontend nunca acessa diretamente)
ALTER TABLE public.company_integrations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS block_all_direct_access ON public.company_integrations;
CREATE POLICY block_all_direct_access ON public.company_integrations
    AS RESTRICTIVE TO anon, authenticated
    USING (FALSE);

-- logs_webhook: inserção somente pelo backend, leitura proibida ao frontend
ALTER TABLE public.logs_webhook ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS block_frontend_access_logs ON public.logs_webhook;
CREATE POLICY block_frontend_access_logs ON public.logs_webhook
    AS RESTRICTIVE TO anon, authenticated
    USING (FALSE);

-- pix_charges: acesso controlado por company_id
-- (Mesmo sem JWT auth, o StorageService já filtra por company_id no app)
-- Conceder permissões ao anon (necessário pois usam anon key no frontend)
GRANT SELECT, INSERT, UPDATE ON public.company_integrations TO service_role;
GRANT INSERT ON public.logs_webhook TO service_role;
GRANT SELECT ON public.logs_webhook TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- Garantir que anon pode operar nas tabelas operacionais (app usa anon key)
GRANT ALL ON public.pix_charges TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.pix_charges_id_seq TO anon, authenticated;
GRANT ALL ON public.company_integrations TO service_role;
GRANT ALL ON public.logs_webhook TO service_role;

-- ============================================================================
-- 7. VERIFICAÇÕES FINAIS — Garantir company_id em todas as tabelas financeiras
-- ============================================================================
ALTER TABLE public.clients      ADD COLUMN IF NOT EXISTS company_id INT REFERENCES public.companies(id);
ALTER TABLE public.loans        ADD COLUMN IF NOT EXISTS company_id INT REFERENCES public.companies(id);
ALTER TABLE public.installments ADD COLUMN IF NOT EXISTS company_id INT REFERENCES public.companies(id);
ALTER TABLE public.payments     ADD COLUMN IF NOT EXISTS company_id INT REFERENCES public.companies(id);

-- Índices para performance em queries multi-tenant
CREATE INDEX IF NOT EXISTS idx_clients_company_id      ON public.clients(company_id);
CREATE INDEX IF NOT EXISTS idx_loans_company_id        ON public.loans(company_id);
CREATE INDEX IF NOT EXISTS idx_installments_company_id ON public.installments(company_id);
CREATE INDEX IF NOT EXISTS idx_payments_company_id     ON public.payments(company_id);
CREATE INDEX IF NOT EXISTS idx_pix_charges_company_id  ON public.pix_charges(company_id);

-- ============================================================================
-- 8. SEED: Gerar webhook_token para empresas que ainda não têm
-- ============================================================================
UPDATE public.company_integrations
SET webhook_token = encode(gen_random_bytes(32), 'hex')
WHERE webhook_token IS NULL OR webhook_token = '';

-- ============================================================================
-- ✅ FIM DA MIGRATION V2
-- PRÓXIMOS PASSOS:
-- 1. Adicionar MASTER_ENCRYPTION_KEY como Secret nas Supabase Edge Functions settings
-- 2. Fazer deploy das Edge Functions atualizadas
-- 3. No admin UI, reconfigurar a API Key de cada empresa (será criptografada)
-- 4. No painel ASAAS de cada empresa, cadastrar a Webhook URL gerada
-- ============================================================================
