-- Migration for Master Admin and Billing System

-- 1. Update users table with new columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS access_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS access_override BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_access_at TIMESTAMP WITH TIME ZONE;

-- Normalize role case/values if needed (ensure role is text and can handle MASTER/ADMIN)
-- The default is 'cliente', we will use 'MASTER' and 'ADMIN' for management

-- 2. Create billing_installments table
CREATE TABLE IF NOT EXISTS billing_installments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    competence_month TEXT NOT NULL, -- Format: YYYY-MM
    due_date DATE NOT NULL,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 10.00,
    status TEXT NOT NULL DEFAULT 'A_VENCER', -- A_VENCER, VENCIDA, PAGA
    paid_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. RLS Policies (Fixed for Integer ID vs UUID match)
ALTER TABLE billing_installments ENABLE ROW LEVEL SECURITY;

-- MASTER sees everything
-- Logic: Check if the email in the Supabase Auth JWT belongs to a MASTER user or the specific master email
DROP POLICY IF EXISTS master_manage_all_billing ON billing_installments;
CREATE POLICY master_manage_all_billing ON billing_installments
    FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM users 
            WHERE email = (auth.jwt() ->> 'email') 
            AND (role = 'MASTER' OR role = 'master' OR email = 'ivanrossi@outlook.com')
        )
        OR (auth.jwt() ->> 'email') = 'ivanrossi@outlook.com'
    );

-- ADMIN sees their own installments
-- Logic: Map the user_id (integer) to the authenticated user's email in the users table
DROP POLICY IF EXISTS admin_view_own_billing ON billing_installments;
CREATE POLICY admin_view_own_billing ON billing_installments
    FOR SELECT
    TO authenticated
    USING (
        user_id IN (
            SELECT id FROM users 
            WHERE email = (auth.jwt() ->> 'email')
        )
    );


-- 4. Initial Master Admin Seed (optional, will also be handled by JS init)
-- Note: id might be serial or uuid, using fallback logic in JS is safer.
