-- 1. Tabela de Logs do Sistema
CREATE TABLE IF NOT EXISTS system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    user_email TEXT,
    action TEXT NOT NULL, -- 'CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'BACKUP', etc.
    module TEXT NOT NULL, -- 'COMPANIES', 'USERS', 'LOANS', 'SETTINGS', etc.
    details JSONB,        -- Dados antes/depois ou descrição extra
    ip_address TEXT
);

-- Habilitar RLS para Logs (Apenas Master pode ver tudo)
ALTER TABLE system_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Master sees all logs" 
ON system_logs FOR SELECT 
USING (auth.jwt() ->> 'email' = 'ivanrossi@outlook.com');

CREATE POLICY "Admins see company logs" 
ON system_logs FOR SELECT 
USING (company_id = (auth.jwt() ->> 'company_id')::bigint);

-- 2. Função para registro de log (Trigger ou Manual via JS)
-- Por simplicidade e controle, usaremos via JS no StorageService.

-- 3. Nota sobre Backups:
-- O Supabase já faz backups automáticos diários. 
-- Para o "Botão de Backup no Servidor", criaremos uma tabela `backups_history` 
-- para registrar quando um backup manual foi solicitado e o status.

CREATE TABLE IF NOT EXISTS backups_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    requested_by UUID REFERENCES auth.users(id),
    status TEXT DEFAULT 'COMPLETED', -- 'PENDING', 'COMPLETED', 'FAILED'
    storage_path TEXT, -- Link para o arquivo no Supabase Storage se necessário
    file_size BIGINT
);
